trigger:
- '*'

variables:
  webRepository: 'web'
  tag: '$(Build.BuildId)'
  acrName: 'tailspinspacegameqq'
  dockerRegistryServiceConnection: 'Container Registry Connection'

stages:
- stage: Build
  displayName: 'Build and push Docker image'
  jobs: 
  - job: Build
    displayName: 'Build Docker container'
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
    - checkout: self

    - task: Docker@2
      displayName: 'Build and push image to ACR'
      inputs:
        command: buildAndPush
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(webRepository)'
        dockerfile: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web'
        tags: |
          $(tag)

- stage: Deploy
  displayName: 'Deploy the container to App Service'
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: 'Deploy job'
    pool:
      vmImage: 'ubuntu-20.04'
    variables:
    - group: Release
    steps:
    - task: AzureWebAppContainer@1
      displayName: 'Deploy container to App Service'
      inputs:
        azureSubscription: 'Resource Manager - Tailspin - Space Game'
        appName: '$(WebAppName)'
        containers: '$(acrName)/$(webRepository):$(tag)'
